### PR TITLE
Env vars to edit master.cf

### PR DESCRIPTION
**Pull request by VeselaHouba**
Option to pass postconf variables which will modify `master.cf`. Maybe there's more elegant way to pass to variable name `/` than replacing with `__` ¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by wader** [comment]
Good idea and yes seem "_" is the only non-letter symbol allowed in environment variables? i can't come up with any better solution. But maybe can give it a day or two to think about alternatives else merge?

**Comment by wader** [comment]
Thanks for taking time to contribute btw!

**Comment by VeselaHouba** [comment]
Well I didn't know about bash parameter expansion with `!` until yesterday 😄  But yeah, let's leave it for few days. I've built forked image, so I can continue with other tests for now.

**Comment by wader** [comment]
Hehe ! can give some unintended surprises yes :) what could be the other options, something involving upper/lower chars, part of the "key" in the value instead, somehow detect known global options "prefixes"? none of them better than __ i think?

**Comment by wader** [comment]
Any breakthroughs? :)

**Comment by VeselaHouba** [comment]
No, not really. I would suggest merging as-is and if some bright mind comes with some cool solution, you can always switch later.

**Comment by wader** [comment]
Sounds good and in that case supporting "__" to be backwards compatible is probably not a problem.

**Comment by wader** [comment]
And thanks for contributing!

**Pull request merged**
